services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    volumes:
      - ./client:/app/client:delegated
      - /app/client/node_modules
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - CESIUM_ION_TOKEN=${CESIUM_ION_TOKEN}
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app:delegated
    ports:
      - "127.0.0.1:3003:3003"
    environment:
      - ENVIRONMENT=development
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=db_dev_user
      - PG_PASSWORD=DevPassword
      - PG_DB=db_dev
      - SERVER_PORT=3003
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3003/api/v1/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
  db:
    image: postgis/postgis:13-3.3-alpine
    restart: always
    environment:
      POSTGRES_USER: db_dev_user
      POSTGRES_PASSWORD: DevPassword
      POSTGRES_DB: db_dev
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: psql -U db_dev_user -d db_dev -c "SELECT 1"
      interval: 5s
      timeout: 5s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin  # Change this to something secure
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgladmin
    depends_on:
      - db
    restart: unless-stopped

  geoserver:
    image: kartoza/geoserver:2.24.1
    container_name: maapallo-geoserver
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - INITIAL_MEMORY=512M
      - MAXIMUM_MEMORY=1G
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db_dev
      - POSTGRES_USER=db_dev_user
      - POSTGRES_PASS=DevPassword
      - SAMPLE_DATA=false
      - GEOSERVER_CSRF_DISABLED=true
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - ./geoserver/data:/opt/geoserver/upload_data
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080/geoserver/web/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db-volume:
  pgadmin-data:
  geoserver-data:
