[tool.black]
line-length = 79
target-version = ['py313']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
)/
'''

[tool.flake8]
max-line-length = 79
ignore = ["E203", "W503"]
