INSERT INTO feature (title, author, thumbnail, excerpt, publication, link, location) VALUES
('Climate Change in Africa', 'A. Researcher', NULL, 'An overview of climate change impacts in Africa.', 'Nature Journal', 'https://example.com/article1', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[35.7796,-6.1630]}'), 3067)),
('Wildlife Corridors', 'B. Ecologist', 'https://example.com/thumb2.jpg', 'How wildlife corridors help preserve biodiversity.', 'Science Daily', 'https://example.com/article2', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[37.2692,-13.2543]}'), 3067)),
('Water Scarcity Solutions', 'C. Hydrologist', NULL, 'Innovative solutions to water scarcity in arid regions.', 'Water World', 'https://example.com/article3', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[-13.0033,25.0000]}'), 3067)),
('Urbanization Trends', 'D. Urbanist', 'https://example.com/thumb4.jpg', 'Urban growth and its environmental impacts.', 'Urban Studies', 'https://example.com/article4', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[35.2033,31.9522]}'), 3067)),
('Mangrove Restoration', 'E. Biologist', NULL, 'Restoring mangroves for coastal protection.', 'Eco Magazine', 'https://example.com/article5', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[121.0794,-2.1115]}'), 3067)),
('Desertification in Sahel', 'F. Geographer', 'https://example.com/thumb6.jpg', 'Fighting desertification in the Sahel region.', 'Geo Times', 'https://example.com/article6', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[1.0000,15.0000]}'), 3067)),
('Renewable Energy Projects', 'G. Engineer', NULL, 'Solar and wind energy projects in North Africa.', 'Energy Today', 'https://example.com/article7', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[10.0000,30.0000]}'), 3067)),
('Rainforest Conservation', 'H. Conservationist', 'https://example.com/thumb8.jpg', 'Efforts to conserve rainforests in Indonesia.', 'Forest News', 'https://example.com/article8', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[120.0000,-1.0000]}'), 3067)),
('Agricultural Innovation', 'I. Agronomist', NULL, 'New techniques for sustainable agriculture.', 'Agri Journal', 'https://example.com/article9', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[40.0000,-10.0000]}'), 3067)),
('Coral Reef Protection', 'J. Marine Biologist', 'https://example.com/thumb10.jpg', 'Protecting coral reefs from bleaching.', 'Marine Science', 'https://example.com/article10', ST_SetSRID(ST_GeomFromGeoJSON('{"type":"Point","coordinates":[150.0000,-20.0000]}'), 3067));

