name: Build, Test and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  ACR_REGISTRY: maapalloregistry.azurecr.io
  APP_NAME: maapallo-info-app
  RESOURCE_GROUP: maapallo-info-group

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}, ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}:latest
          build-args: |
            CESIUM_ION_TOKEN=${{ secrets.CESIUM_ION_TOKEN }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          images: ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Configure App Service Environment Variables
        run: |
          echo "Setting up environment variables..."
          az webapp config appsettings set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME }} \
            --settings \
              ADMIN_USERNAME="${{ secrets.ADMIN_USERNAME }}" \
              ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" \
              JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              CESIUM_ION_TOKEN="${{ secrets.CESIUM_ION_TOKEN }}" \
              ENVIRONMENT="production"

          # Option 1: Use Azure's existing database secrets (recommended)
          echo "✅ Using Azure Key Vault/App Configuration for database secrets (PG_*)"

          # Option 2: Uncomment below if you want to use GitHub secrets for database
          # az webapp config appsettings set \
          #   --resource-group ${{ env.RESOURCE_GROUP }} \
          #   --name ${{ env.APP_NAME }} \
          #   --settings \
          #     PG_HOST="${{ secrets.PG_HOST }}" \
          #     PG_PORT="${{ secrets.PG_PORT }}" \
          #     PG_DATABASE="${{ secrets.PG_DATABASE }}" \
          #     PG_USER="${{ secrets.PG_USER }}" \
          #     PG_PASS="${{ secrets.PG_PASS }}" \
          #     PG_SSLMODE="${{ secrets.PG_SSLMODE }}"

      - name: Run migrations and restart Web App
        run: |
          echo "Running migrations via API endpoint..."
          # Wait for app to be available
          sleep 30

          # Try to run migrations via API
          curl -X POST "https://${{ env.APP_NAME }}.azurewebsites.net/api/v1/admin/migrate" \
            -H "Content-Type: application/json" \
            -d '{"username": "${{ secrets.ADMIN_USERNAME }}", "password": "${{ secrets.ADMIN_PASSWORD }}"}' || echo "Migration endpoint call failed - app may not be ready yet"

          echo "Restarting web app..."
          az webapp restart --name ${{ env.APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}
          echo "✅ Web app restarted - using direct uvicorn startup"
